
#ifndef EFFECTCOMPOSITOR_API_H
#define EFFECTCOMPOSITOR_API_H

#ifdef EFFECTCOMPOSITOR_STATIC_DEFINE
#  define EFFECTCOMPOSITOR_API
#  define EFFECTCOMPOSITOR_NO_EXPORT
#else
#  ifndef EFFECTCOMPOSITOR_API
#    ifdef EffectCompositor_EXPORTS
        /* We are building this library */
#      define EFFECTCOMPOSITOR_API 
#    else
        /* We are using this library */
#      define EFFECTCOMPOSITOR_API 
#    endif
#  endif

#  ifndef EFFECTCOMPOSITOR_NO_EXPORT
#    define EFFECTCOMPOSITOR_NO_EXPORT 
#  endif
#endif

#ifndef EFFECTCOMPOSITOR_DEPRECATED
#  define EFFECTCOMPOSITOR_DEPRECATED __declspec(deprecated)
#endif

#ifndef EFFECTCOMPOSITOR_DEPRECATED_EXPORT
#  define EFFECTCOMPOSITOR_DEPRECATED_EXPORT EFFECTCOMPOSITOR_API EFFECTCOMPOSITOR_DEPRECATED
#endif

#ifndef EFFECTCOMPOSITOR_DEPRECATED_NO_EXPORT
#  define EFFECTCOMPOSITOR_DEPRECATED_NO_EXPORT EFFECTCOMPOSITOR_NO_EXPORT EFFECTCOMPOSITOR_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef EFFECTCOMPOSITOR_NO_DEPRECATED
#    define EFFECTCOMPOSITOR_NO_DEPRECATED
#  endif
#endif

#endif /* EFFECTCOMPOSITOR_API_H */
